version: '3.9'
services:
  db:
    container_name: db
    image: postgres:17.3
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=booking
    ports:
      - "5432:5432"
    volumes:
      - .docker/data:/var/lib/postgresql/data
