version: '3.9'
networks:
  booking:
services:
  db:
    container_name: db
    image: postgres:17.3
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=booking
    ports:
      - "5432:5432"
    volumes:
      - .docker/data:/var/lib/postgresql/data
    networks:
      - booking
  go:
    container_name: go
    build:
      context: .docker
      dockerfile: go.dockerfile
      args:
        UID: ${UID:-1000}
        GID: ${GID:-1000}
    volumes:
      - .:/app
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - booking
